#!/usr/bin/env bash
# Find and stop the 4-to_infinity_and_beyond process using kill

# Find PID of the process
process_name="4-to_infinity_and_beyond"
pid=$(pgrep -f "$process_name")

if [ -n "$pid" ]; then
    echo "Stopping process with name '$process_name' and PID $pid"
    # Send SIGTERM signal to gracefully stop the process
    kill "$pid"
else
    echo "Process with name '$process_name' is not running"
fi

